name: Build and Deploy BackendApp to ECS

on:
  push:
    branches:
      - main

env:
  ECR_REPOSITORY: flask-app
  ECS_SERVICE: ecs-flask-service-v2
  ECS_CLUSTER: tradechat-v1-Cluster-gCKiEfF6ACNl
  ECS_TASK_DEFINITION: .github/workflows/task-definition.json
  CONTAINER_NAME: "flask"
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com

      - name: Build and push Docker image
        id: build-image
        run: |
          cd APP
          docker build -t flask .
          docker tag flask:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/flask:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/flask:latest
          echo "image=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/flask:latest" >> $GITHUB_OUTPUT
      
      - name: Prepare task definition
        run: |
          sed -e "s|__AWS_ACCOUNT_ID__|${{ secrets.AWS_ACCOUNT_ID }}|g" \
              -e "s|__AWS_DEFAULT_REGION__|${{ secrets.AWS_DEFAULT_REGION }}|g" \
              .github/workflows/task-definition-template.json > .github/workflows/task-definition.json
              
      - name: Stop existing ECS tasks
        run: |
          existing_tasks=$(aws ecs list-tasks --cluster ${{ env.ECS_CLUSTER }} --service-name ${{ env.ECS_SERVICE }} --query 'taskArns' --output text)
          if [ "$existing_tasks" != "None" ]; then
            for task in $existing_tasks; do
              aws ecs stop-task --cluster ${{ env.ECS_CLUSTER }} --task $task
            done
          fi
      
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
