name: Build and Deploy BackendApp to ECS


on:
  push:
    path:
      - 'APP/**'
    branches:
      - main
env:
  #Setting an envrioment variable for the AWS region
  ECR_BACKEND_IMAGE: ${{ vars.ECR_BACKEND_IMAGE }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_BACKED_SERVICE: ${{ secrets.ECS_BACKED_SERVICE }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}
      - name: Build the Docker image
        run: docker build -t ${{ secrets.AWS_ECR_URL }}/$ECR_BACKEND_IMAGE .
      - name: Push the Docker image to ECR
        run: docker push ${{ secrets.AWS_ECR_URL }}/$ECR_BACKEND_IMAGE
      - name: Update ECS service
        run: aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_BACKED_SERVICE }} --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 